// Build pipeline for the bike catalogue (Step 3). The CLI is scripts/build-bike-catalog.mjs.
//
//   data/bikes/**.json  ──validate──►  runtime bundles  ──►  public/bikedb/bundles/<hash>.json
//                                            │          ──►  public/bikedb/catalog.json
//                                            └────────────►  build/bikedb/bikes.sqlite   (lib/bikedb/schema.sql)
//
// Rules:
//   * Nothing is written unless the whole catalogue validates (bundle-contract.js).
//     Files in data/bikes/pending/ are never built.
//   * Same input → same output. Output JSON is canonical (sorted keys, no
//     whitespace), with no timestamps, so catalog.json and every bundle are
//     byte-identical across builds and machines. bikes.sqlite is byte-identical
//     for the same SQLite version.
//   * A bundle's file name is the start of the SHA-256 of its bytes, so it can be
//     cached forever: changed data means a new name.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import zlib from "node:zlib";
import { createRequire } from "node:module";
import { ROOT, DATA, Contract, loadCatalog } from "./load-catalog.mjs";

const require = createRequire(import.meta.url);
/** @type {typeof import("../../public/js/bikedb/catalog-search.js")} */
export const Search = require("../../public/js/bikedb/catalog-search.js");

export const BUNDLE_FORMAT = "mapunite-bike-bundle/1";
export const DB_FORMAT = 2;                       // = PRAGMA user_version in lib/bikedb/schema.sql
export const HASH_CHARS = 16;                     // 64 bits of SHA-256, hex (safe on case-insensitive file systems)
export const CATALOG_BUDGET_GZIP = 300 * 1024;    // plan: catalog.json under 300 KB gzipped
export const BUNDLE_PATH = "bundles/{hash}.json";
export const SCHEMA_SQL = path.join(ROOT, "lib", "bikedb", "schema.sql");
export const DEFAULT_PUBLIC_DIR = path.join(ROOT, "public", "bikedb");
export const DEFAULT_DB_FILE = path.join(ROOT, "build", "bikedb", "bikes.sqlite");
const GITIGNORE = "# Generated by scripts/build-bike-catalog.mjs from data/bikes/. Don't edit or commit.\n*\n";
const BUNDLE_FILE_RE = new RegExp(`^[0-9a-f]{${HASH_CHARS}}\\.json$`);

export class BuildError extends Error {
    /** @param {string} message @param {string[]} [details] */
    constructor(message, details = []) {
        super(details.length ? `${message}\n  ${details.join("\n  ")}` : message);
        this.name = "BuildError";
        this.details = details;
    }
}

// ----------------------------------------------------------------------------
// Canonical JSON + hashing
// ----------------------------------------------------------------------------
/**
 * JSON with object keys sorted (code-unit order) at every level and no
 * whitespace. Array order is kept (it carries meaning: gear ratios, sources).
 * Throws on values JSON can't represent faithfully.
 * @param {unknown} value
 * @returns {string}
 */
export function canonicalJson(value) {
    if (value === null) return "null";
    switch (typeof value) {
        case "string": return JSON.stringify(value);
        case "boolean": return value ? "true" : "false";
        case "number":
            if (!Number.isFinite(value)) throw new BuildError(`cannot serialise ${value}`);
            return JSON.stringify(value);
        case "object": {
            if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
            const keys = Object.keys(value).sort();
            return `{${keys.map((k) => {
                if (value[k] === undefined) throw new BuildError(`undefined value at key "${k}"`);
                return `${JSON.stringify(k)}:${canonicalJson(value[k])}`;
            }).join(",")}}`;
        }
        default: throw new BuildError(`cannot serialise a ${typeof value}`);
    }
}

export const sha256 = (text) => crypto.createHash("sha256").update(text, "utf8").digest("hex");
export const shortHash = (text) => sha256(text).slice(0, HASH_CHARS);
export const gzipSize = (text) => zlib.gzipSync(Buffer.from(text, "utf8"), { level: 9 }).length;

// ----------------------------------------------------------------------------
// Runtime bundle: everything the phone needs for one bike, in one file
// ----------------------------------------------------------------------------
const VALUE_GROUPS = ["engine", "motor", "battery", "transmission", "chassis", "emission", "fuel"];
const ICE = ["ice_manual", "ice_cvt"];
const FIELD_BY_PATH = new Map(Contract.FIELDS.map((f) => [f.path, f]));

// ----------------------------------------------------------------------------
// Strict SI (conversions: SI_UNITS in bundle-contract.js)
// ----------------------------------------------------------------------------
/**
 * A sourced quantity { v, u, tol?, … } in SI. When the unit changes, the
 * figure as published is kept under `published` for human review.
 * @param {any} q            { v: number|number[], u: string, tol?, src, conf, … }
 * @param {string} unit      its published unit
 */
export function quantityToSI(q, unit) {
    const si = Contract.siUnit(unit);
    const out = { ...q, v: Contract.toSI(q.v, unit), u: si };
    if (q.tol !== undefined) out.tol = Contract.toSI(q.tol, unit);
    if (si !== unit) out.published = q.tol !== undefined ? { v: q.v, u: unit, tol: q.tol } : { v: q.v, u: unit };
    return out;
}

/** A prior { mean, sigma, u, … } in SI, with the published figures when the unit changes. */
export function priorToSI(p, unit) {
    const si = Contract.siUnit(unit);
    const out = { ...p, mean: Contract.toSI(p.mean, unit), sigma: Contract.toSI(p.sigma, unit), u: si };
    if (si !== unit) out.published = { mean: p.mean, sigma: p.sigma, u: unit };
    return out;
}

/** A digitised curve in SI: angular speed in rad/s, values in N*m or W. */
export function curveToSI(c) {
    const out = { ...c, omegaStart: Contract.toSI(c.rpmStart, "rpm"), omegaStep: Contract.toSI(c.rpmStep, "rpm"), scale: Contract.toSI(c.scale, c.u), u: Contract.siUnit(c.u),
        published: { rpmStart: c.rpmStart, rpmStep: c.rpmStep, scale: c.scale, u: c.u } };
    delete out.rpmStart;
    delete out.rpmStep;
    return out;
}

/** One value group (engine, chassis …) with every quantity and prior in SI; categorical values unchanged. */
function groupToSI(g, node) {
    /** @type {Record<string, any>} */
    const out = {};
    for (const [k, v] of Object.entries(node)) {
        const f = FIELD_BY_PATH.get(`${g}.${k}`);
        if (!f) out[k] = v;                                  // fuel.compat: fuel codes and statuses, no units
        else if (f.type === "q" || f.type === "qa") out[k] = quantityToSI(v, f.unit);
        else if (f.type === "p") out[k] = priorToSI(v, f.unit);
        else out[k] = v;
    }
    return out;
}

/** A fuel-grade row in SI: lhv J/m3, density kg/m3, typicalRon 1. */
function gradeToSI(g) {
    const out = { ...g };
    for (const k of ["lhv", "density", "typicalRon"]) if (g[k]) out[k] = quantityToSI(g[k], g[k].u);
    return out;
}

/** Sources of `list` whose id is in `ids`, in their original order. */
const usedSources = (list, ids) => (list || []).filter((s) => ids.has(s.id));

/**
 * The bundle a phone downloads, in strict SI: every quantity converted (the
 * figure as published kept under `published`), priors resolved through the
 * class default, the fuel-advice decision made by the contract, the reference
 * data the physics needs, and `image_url` for the bike picker (null until a
 * picture is sourced). Self-contained: once fetched it works offline.
 * @param {any} b          validated variant or class default
 * @param {any} classDef   the class default for b.classKey (b itself for a default)
 * @param {import("../../public/js/bikedb/bundle-contract.js").RefTables & Record<string, any>} ref
 * @param {any} [calibration]  the class's fleet calibration (data/bikes/calibration/): its real-riding
 *                             overhead and evidence go into the bundle as `calibration` (roadmap Step 11)
 */
export function makeRuntimeBundle(b, classDef, ref, calibration = null) {
    const isVariant = b.kind === "variant";
    /** @type {Record<string, any>} */
    const rt = {
        format: BUNDLE_FORMAT,
        schemaVersion: b.schemaVersion,
        id: b.id,
        kind: b.kind,
        classKey: b.classKey,
        segment: b.segment,
        powertrain: b.powertrain,
        units: "SI",
        identity: b.identity,
        image_url: b.image ? b.image.url : null,
        sources: b.sources
    };
    if (b.image) rt.image = b.image;                         // the picture's provenance (src, credit)
    for (const g of VALUE_GROUPS) if (b[g] !== undefined && b[g] !== null) rt[g] = groupToSI(g, b[g]);
    if (b.curves) rt.curves = Object.fromEntries(Object.entries(b.curves).map(([k, c]) => [k, curveToSI(c)]));
    if (Array.isArray(b.notes) && b.notes.length) rt.notes = b.notes;

    // Priors: the variant's own, else the class default's (marked inherited; their
    // src refers to classDefault.sources, so ids can never collide with the variant's).
    const priors = {};
    const inheritedSrc = new Set();
    for (const f of Contract.FIELDS) {
        if (!f.path.startsWith("priors.") || !f.allow.includes(b.powertrain)) continue;
        const key = f.path.slice("priors.".length);
        const own = b.priors && b.priors[key];
        if (own) priors[key] = priorToSI(own, f.unit);
        else if (isVariant && classDef.priors && classDef.priors[key]) {
            priors[key] = { ...priorToSI(classDef.priors[key], f.unit), inherited: true };
            inheritedSrc.add(classDef.priors[key].src);
        }
    }
    rt.priors = priors;
    // Fleet calibration (roadmap Step 11): the real-riding overhead learned with the class's priors
    // (dimensionless; its src is the class default's "fleet-calibration" source).
    if (calibration && ICE.includes(b.powertrain)) rt.calibration = { date: calibration.date, tanks: calibration.tanks, riders: calibration.riders, overhead: { ...calibration.overhead } };
    if (isVariant) rt.classDefault = { id: classDef.id, sources: usedSources(classDef.sources, inheritedSrc) };

    if (ICE.includes(b.powertrain)) {
        // The fuel-safety decision, made once here by the contract. The app shows
        // a fuel as recommended only if it's in this list.
        rt.fuelAdvice = {
            minConf: Contract.ADVISE_MIN_CONF,
            advisable: ref.fuelGrades.grades.map((g) => g.code).filter((code) => Contract.isFuelAdvisable(b, code, ref))
        };
        const gradeSrc = new Set(ref.fuelGrades.grades.flatMap((g) => ["lhv", "density", "typicalRon"].filter((k) => g[k]).map((k) => g[k].src)));
        rt.reference = { fuelGrades: { sources: usedSources(ref.fuelGrades.sources, gradeSrc), grades: ref.fuelGrades.grades.map(gradeToSI) } };
        if (b.emission) {
            const std = ref.emissionStandards.standards.find((s) => s.code === b.emission.standard.v);
            const obd = b.emission.obd ? ref.emissionStandards.obdLevels.find((o) => o.code === b.emission.obd.v) : null;
            const ids = new Set([std && std.src, obd && obd.src].filter(Boolean));
            /** @type {Record<string, any>} */
            const em = { sources: usedSources(ref.emissionStandards.sources, ids), standard: std };
            if (obd) em.obd = obd;
            rt.reference.emission = em;
        }
    }
    return rt;
}

// ----------------------------------------------------------------------------
// Catalogue rows
// ----------------------------------------------------------------------------
/** Size shown in the picker, SI: displacement in m3 for petrol bikes, gross battery energy in J for EVs. */
function sizeOf(b) {
    if (b.powertrain === "ev") return b.battery && b.battery.grossCapacity ? Contract.toSI(b.battery.grossCapacity.v, b.battery.grossCapacity.u) : null;
    return b.engine && b.engine.displacement ? Contract.toSI(b.engine.displacement.v, b.engine.displacement.u) : null;
}

const byCode = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

/**
 * catalog.json from search rows. Shared with the synthetic benchmark so it
 * measures exactly what ships.
 * @param {Array<{ id: string, make: string, model: string, variant: string|null, market: string, yearFrom: number, yearTo: number|null, classKey: string, size: number|null, aliases: string[], image_url: string|null, bundle: string }>} rows
 * @param {Array<{ key: string, powertrain: string, segment: string, title: string, image_url: string|null, bundle: string }>} classes
 * @param {string} schemaVersion
 */
export function assembleCatalog(rows, classes, schemaVersion) {
    const sorted = [...rows].sort((a, b) => byCode(a.make, b.make) || byCode(a.model, b.model) || byCode(a.variant || "", b.variant || "") || byCode(a.id, b.id));
    const makes = [...new Set(sorted.map((r) => r.make))].sort(byCode);
    const makeIdx = new Map(makes.map((m, i) => [m, i]));
    const classIdx = new Map(classes.map((c, i) => [c.key, i]));
    for (const r of sorted) if (!classIdx.has(r.classKey)) throw new BuildError(`${r.id}: class ${r.classKey} has no class default`);
    const column = {
        id: (r) => r.id, make: (r) => makeIdx.get(r.make), model: (r) => r.model, variant: (r) => r.variant, market: (r) => r.market,
        yearFrom: (r) => r.yearFrom, yearTo: (r) => r.yearTo, class: (r) => classIdx.get(r.classKey), size: (r) => r.size,
        aliases: (r) => r.aliases, image_url: (r) => (r.image_url === undefined ? null : r.image_url), bundle: (r) => r.bundle
    };
    const body = {
        format: Search.CATALOG_FORMAT,
        schemaVersion,
        units: "SI",
        bundlePath: BUNDLE_PATH,
        makes,
        classes,
        count: sorted.length,
        columns: Object.fromEntries(Search.CATALOG_COLUMNS.map((k) => [k, sorted.map(column[k])]))
    };
    const version = shortHash(canonicalJson(body));
    const catalog = { ...body, version };
    return { catalog, version, bytes: canonicalJson(catalog), rows: sorted };
}

// ----------------------------------------------------------------------------
// The build, in memory
// ----------------------------------------------------------------------------
/**
 * Validate and build every artifact in memory. Throws BuildError (and writes
 * nothing) if the catalogue doesn't validate.
 * @param {{ entries: Array<{ file?: string, bundle: any }>, ref: any, calibrations?: Map<string, any> }} input  loadCatalog() output
 */
export function buildArtifacts({ entries, ref, calibrations = new Map() }) {
    const report = Contract.validateCatalog(entries, ref);
    if (!report.ok) {
        const details = [];
        for (const { file, result } of report.perFile) for (const e of result.errors) details.push(`${file} ${e.path}: ${e.message} [${e.code}]`);
        for (const e of report.errors) details.push(`${e.path}: ${e.message} [${e.code}]`);
        throw new BuildError("the bike catalogue doesn't validate — nothing was built (run node scripts/bikedb/validate.mjs)", details);
    }
    const warnings = report.warnings.length + report.perFile.reduce((n, p) => n + p.result.warnings.length, 0);

    const defaults = new Map(entries.filter((e) => e.bundle.kind === "class_default").map((e) => [e.bundle.classKey, e.bundle]));
    const classKeys = Object.entries(Contract.CLASS_MATRIX).flatMap(([pt, segs]) => segs.map((s) => `${pt}.${s}`));
    const variants = entries.filter((e) => e.bundle.kind === "variant").map((e) => e.bundle).sort((a, b) => byCode(a.id, b.id));

    /** @type {Array<{ id: string, kind: string, classKey: string, hash: string, bytes: string, runtime: any, source: any }>} */
    const bundles = [];
    const byHash = new Map();
    const add = (b, classDef) => {
        const runtime = makeRuntimeBundle(b, classDef, ref, calibrations.get(b.classKey) || null);
        const bytes = canonicalJson(runtime);
        const hash = shortHash(bytes);
        if (byHash.has(hash)) throw new BuildError(`bundle hash collision: ${b.id} and ${byHash.get(hash)} both hash to ${hash}`);
        byHash.set(hash, b.id);
        const out = { id: b.id, kind: b.kind, classKey: b.classKey, hash, bytes, runtime, source: b };
        bundles.push(out);
        return out;
    };
    const classes = classKeys.map((key) => {
        const d = defaults.get(key);
        const built = add(d, d);
        return { key, powertrain: d.powertrain, segment: d.segment, title: d.identity.model, image_url: d.image ? d.image.url : null, bundle: built.hash };
    });
    const rows = variants.map((b) => {
        const built = add(b, defaults.get(b.classKey));
        return {
            id: b.id, make: b.identity.make, model: b.identity.model, variant: b.identity.variant === undefined ? null : b.identity.variant,
            market: b.identity.market, yearFrom: b.identity.yearFrom, yearTo: b.identity.yearTo,
            classKey: b.classKey, size: sizeOf(b), aliases: b.identity.aliases, image_url: b.image ? b.image.url : null, bundle: built.hash
        };
    });
    const schemaVersion = Contract.SCHEMA_VERSION;
    const cat = assembleCatalog(rows, classes, schemaVersion);
    const gz = gzipSize(cat.bytes);
    if (gz > CATALOG_BUDGET_GZIP) throw new BuildError(`catalog.json is ${(gz / 1024).toFixed(1)} KB gzipped, over the ${CATALOG_BUDGET_GZIP / 1024} KB budget`);

    // Fingerprint of the INPUT (canonical, so formatting-only edits don't change it).
    const inputHash = sha256(canonicalJson({
        bundleFormat: BUNDLE_FORMAT, dbFormat: DB_FORMAT, schemaVersion,
        bundles: entries.map((e) => e.bundle).sort((a, b) => byCode(a.id, b.id)),
        ref,
        calibrations: [...calibrations.entries()].sort((a, b) => byCode(a[0], b[0]))
    }));
    return {
        bundles,
        catalog: { object: cat.catalog, bytes: cat.bytes, version: cat.version, rows: cat.rows, gzipBytes: gz },
        classes,
        inputHash,
        schemaVersion,
        counts: { variants: variants.length, classDefaults: classes.length, warnings }
    };
}

// ----------------------------------------------------------------------------
// Writing public/bikedb/
// ----------------------------------------------------------------------------
/** Write via a temp file + rename, so a reader never sees half a file. */
function writeAtomic(file, text) {
    const tmp = `${file}.tmp-${process.pid}`;
    fs.writeFileSync(tmp, text);
    fs.renameSync(tmp, file);
}

/**
 * Write catalog.json and bundles/<hash>.json. Bundles go first and catalog.json
 * last, so a catalogue never points at a bundle that isn't there yet.
 * Unchanged bundles aren't rewritten. With prune (the default), bundle files
 * that no longer belong to the catalogue are removed, so the folder is exactly
 * the build output.
 * @param {ReturnType<typeof buildArtifacts>} art
 * @param {string} dir
 * @param {{ prune?: boolean }} [opts]
 */
export function writePublic(art, dir, { prune = true } = {}) {
    const bdir = path.join(dir, "bundles");
    fs.mkdirSync(bdir, { recursive: true });
    const gi = path.join(dir, ".gitignore");
    if (!fs.existsSync(gi)) fs.writeFileSync(gi, GITIGNORE);
    let written = 0, unchanged = 0, pruned = 0, bundleBytes = 0;
    const keep = new Set();
    for (const b of art.bundles) {
        const name = `${b.hash}.json`;
        keep.add(name);
        bundleBytes += Buffer.byteLength(b.bytes);
        const file = path.join(bdir, name);
        if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === b.bytes) { unchanged++; continue; }
        writeAtomic(file, b.bytes);
        written++;
    }
    writeAtomic(path.join(dir, "catalog.json"), art.catalog.bytes);
    if (prune) {
        for (const f of fs.readdirSync(bdir)) {
            const stale = (BUNDLE_FILE_RE.test(f) && !keep.has(f)) || /\.json\.tmp-\d+$/.test(f);
            if (stale) { fs.rmSync(path.join(bdir, f)); pruned++; }
        }
    }
    return { written, unchanged, pruned, bundleBytes, catalogBytes: Buffer.byteLength(art.catalog.bytes), catalogGzip: art.catalog.gzipBytes };
}

/**
 * Compare public/bikedb/ with a fresh build. Returns a list of differences.
 * @param {ReturnType<typeof buildArtifacts>} art
 * @param {string} dir
 */
export function diffPublic(art, dir) {
    const diffs = [];
    const cat = path.join(dir, "catalog.json");
    if (!fs.existsSync(cat)) diffs.push("catalog.json is missing");
    else if (fs.readFileSync(cat, "utf8") !== art.catalog.bytes) diffs.push("catalog.json is out of date");
    const bdir = path.join(dir, "bundles");
    const want = new Map(art.bundles.map((b) => [`${b.hash}.json`, b]));
    const have = fs.existsSync(bdir) ? fs.readdirSync(bdir).filter((f) => BUNDLE_FILE_RE.test(f)) : [];
    for (const [name, b] of want) {
        const file = path.join(bdir, name);
        if (!fs.existsSync(file)) diffs.push(`bundles/${name} (${b.id}) is missing`);
        else if (fs.readFileSync(file, "utf8") !== b.bytes) diffs.push(`bundles/${name} (${b.id}) doesn't match its hash`);
    }
    for (const f of have) if (!want.has(f)) diffs.push(`bundles/${f} is stale`);
    return diffs;
}

// ----------------------------------------------------------------------------
// Writing bikes.sqlite
// ----------------------------------------------------------------------------
const n0 = (x) => (x === undefined ? null : x);
const flag = (x) => (x ? 1 : 0);

/**
 * Build bikes.sqlite from the artifacts, into a temp file renamed into place
 * at the end, so a reader never sees a half-built database.
 * @param {ReturnType<typeof buildArtifacts>} art
 * @param {any} ref
 * @param {string} file
 * @param {{ name: string, open: (file: string, o?: any) => import("./sqlite-driver.mjs").Db }} driver
 */
export function writeSqlite(art, ref, file, driver) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const gi = path.join(path.dirname(file), ".gitignore");
    if (!fs.existsSync(gi)) fs.writeFileSync(gi, GITIGNORE);
    const tmp = `${file}.tmp-${process.pid}`;
    for (const f of [tmp, `${tmp}-journal`]) fs.rmSync(f, { force: true });
    const db = driver.open(tmp);
    let sqliteVersion;
    try {
        sqliteVersion = db.sqliteVersion;
        db.exec("PRAGMA page_size = 4096; PRAGMA journal_mode = DELETE; PRAGMA foreign_keys = ON;");
        db.exec(fs.readFileSync(SCHEMA_SQL, "utf8"));
        const uv = db.prepare("PRAGMA user_version").get();
        if (Number(Object.values(uv)[0]) !== DB_FORMAT) throw new BuildError(`lib/bikedb/schema.sql has user_version ${Object.values(uv)[0]}, but the build expects ${DB_FORMAT}`);
        db.transaction(() => fillDb(db, art, ref, sqliteVersion));
        const fk = db.prepare("PRAGMA foreign_key_check").all();
        if (fk.length) throw new BuildError("bikes.sqlite: foreign-key violations", fk.map((r) => JSON.stringify(r)));
        const ic = db.prepare("PRAGMA integrity_check").all().map((r) => Object.values(r)[0]);
        if (ic.length !== 1 || ic[0] !== "ok") throw new BuildError("bikes.sqlite: integrity check failed", ic.map(String));
        db.exec("INSERT INTO bundle_search(bundle_search) VALUES ('optimize');");
        db.exec("VACUUM;");
    } catch (e) {
        fs.rmSync(tmp, { force: true });
        throw e;
    } finally {
        try { db.close(); } catch { /* ignore */ }
    }
    try {
        fs.renameSync(tmp, file);
    } catch (e) {
        fs.rmSync(tmp, { force: true });
        if (e && (e.code === "EBUSY" || e.code === "EPERM")) throw new BuildError(`can't replace ${path.relative(ROOT, file)}: it's open in another program (stop the server and build again)`);
        throw e;
    }
    return { file, bytes: fs.statSync(file).size, driver: driver.name, sqliteVersion };
}

function fillDb(db, art, ref, sqliteVersion) {
    const ins = (sql) => db.prepare(sql);
    const meta = ins("INSERT INTO meta (key, value) VALUES (?, ?)");
    for (const [k, v] of [["db_format", String(DB_FORMAT)], ["schema_version", art.schemaVersion], ["bundle_format", BUNDLE_FORMAT],
        ["catalog_format", Search.CATALOG_FORMAT], ["catalog_version", art.catalog.version], ["input_hash", art.inputHash], ["sqlite_version", sqliteVersion]]) meta.run(k, v);

    const field = ins("INSERT INTO field (path, grp, value_type, unit, published_unit, si_factor, range_min, range_max, doc) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    for (const f of Contract.FIELDS) {
        const q = f.type !== "c";
        field.run(f.path, f.path.split(".")[0], f.type, q ? Contract.siUnit(f.unit) : null, q ? f.unit : null, q ? Contract.toSI(1, f.unit) : null,
            f.range && q ? Contract.toSI(f.range[0], f.unit) : null, f.range && q ? Contract.toSI(f.range[1], f.unit) : null, f.doc);
    }

    const vclass = ins("INSERT INTO vehicle_class (class_key, powertrain, segment) VALUES (?, ?, ?)");
    for (const c of art.classes) vclass.run(c.key, c.powertrain, c.segment);

    // ---- reference tables ----
    const refSrc = ins("INSERT INTO ref_source (ref_table, source_key, ord, kind, title, url, publisher, retrieved, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    for (const [table, t] of [["fuel-grades", ref.fuelGrades], ["emission-standards", ref.emissionStandards]]) {
        (t.sources || []).forEach((s, i) => refSrc.run(table, s.id, i, s.kind, s.title, n0(s.url), n0(s.publisher), s.retrieved, n0(s.note)));
    }
    const grade = ins("INSERT INTO fuel_grade (code, ord, ethanol_vol_fraction, flex_fuel_blend) VALUES (?, ?, ?, ?)");
    const gradeProp = ins("INSERT INTO fuel_grade_property (code, property, value, unit, published_value, published_unit, source_key, conf, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    ref.fuelGrades.grades.forEach((g, i) => {
        grade.run(g.code, i, g.ethanolVolFraction, flag(g.flexFuelBlend));
        for (const p of ["lhv", "density", "typicalRon"]) {
            if (g[p]) gradeProp.run(g.code, p, Contract.toSI(g[p].v, g[p].u), Contract.siUnit(g[p].u), g[p].v, g[p].u, g[p].src, g[p].conf, n0(g[p].note));
        }
    });
    const obd = ins("INSERT INTO obd_level (code, name, effective_from, source_key, conf, note) VALUES (?, ?, ?, ?, ?, ?)");
    for (const o of ref.emissionStandards.obdLevels) obd.run(o.code, o.name, o.effectiveFrom, o.src, o.conf, n0(o.note));
    const std = ins("INSERT INTO emission_standard (code, name, region, effective_from, superseded_from, obd_at_intro, source_key, conf, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    for (const s of ref.emissionStandards.standards) std.run(s.code, s.name, s.region, s.effectiveFrom, n0(s.supersededFrom), n0(s.obdAtIntro), s.src, s.conf, n0(s.note));

    // ---- makes and models (variants only) ----
    const makeId = new Map(), modelId = new Map();
    const mk = ins("INSERT INTO make (make_id, name) VALUES (?, ?)");
    const md = ins("INSERT INTO model (model_id, make_id, name) VALUES (?, ?, ?)");
    for (const name of art.catalog.object.makes) { makeId.set(name, makeId.size + 1); mk.run(makeId.size, name); }
    for (const r of art.catalog.rows) {
        const key = `${r.make}\u0000${r.model}`;
        if (!modelId.has(key)) { modelId.set(key, modelId.size + 1); md.run(modelId.size, makeId.get(r.make), r.model); }
    }

    // ---- bundles: class defaults (class order), then variants (catalogue order) ----
    const order = [...art.bundles.filter((b) => b.kind === "class_default"),
        ...art.catalog.rows.map((r) => art.bundles.find((b) => b.id === r.id))];
    const bundle = ins("INSERT INTO bundle (bundle_id, slug, kind, class_key, model_id, variant_name, title, market, year_from, year_to, schema_version, image_url, hash, body) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    const cdef = ins("INSERT INTO class_default (class_key, bundle_id) VALUES (?, ?)");
    const alias = ins("INSERT INTO alias (bundle_id, ord, alias) VALUES (?, ?, ?)");
    const source = ins("INSERT INTO source (bundle_id, source_key, ord, kind, title, url, publisher, retrieved, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    const spec = ins(`INSERT INTO spec_value (bundle_id, path, value, vals, txt, flag, tol, qualifier, source_key, conf, note, published_value, published_vals, published_tol)
                      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
    const prior = ins("INSERT INTO prior (bundle_id, path, mean, sigma, source_key, conf, note, published_mean, published_sigma) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    const curve = ins(`INSERT INTO curve (bundle_id, kind, omega_start, omega_step, scale, unit, published_rpm_start, published_rpm_step, published_scale, published_unit, data, method, source_key, conf, note)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
    const note = ins("INSERT INTO note (bundle_id, ord, text) VALUES (?, ?, ?)");
    const compat = ins("INSERT INTO fuel_compat (bundle_id, fuel_code, ord, status, source_key, conf, note, advisable) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
    const fts = ins("INSERT INTO bundle_search (rowid, make, model, variant, aliases) VALUES (?, ?, ?, ?, ?)");

    order.forEach((art_b, i) => {
        const id = i + 1;
        const b = art_b.source;
        const idn = b.identity;
        const isVariant = b.kind === "variant";
        const title = [idn.make, idn.model, idn.variant].filter(Boolean).join(" ");
        bundle.run(id, b.id, b.kind, b.classKey, isVariant ? modelId.get(`${idn.make}\u0000${idn.model}`) : null, n0(idn.variant), title,
            idn.market, idn.yearFrom, idn.yearTo, b.schemaVersion, b.image ? b.image.url : null, art_b.hash, art_b.bytes);
        if (!isVariant) cdef.run(b.classKey, id);
        idn.aliases.forEach((a, j) => alias.run(id, j, a));
        b.sources.forEach((s, j) => source.run(id, s.id, j, s.kind, s.title, n0(s.url), n0(s.publisher), s.retrieved, n0(s.note)));
        for (const f of Contract.FIELDS) {
            const [g, k] = f.path.split(".");
            const v = b[g] && b[g][k];
            if (!v) continue;
            if (f.type === "p") {
                prior.run(id, f.path, Contract.toSI(v.mean, f.unit), Contract.toSI(v.sigma, f.unit), v.src, v.conf, n0(v.note), v.mean, v.sigma);
                continue;
            }
            const extraKey = Object.keys(f.extra || {})[0];
            const q = f.type === "q", qa = f.type === "qa", cat = f.type === "c";
            spec.run(id, f.path,
                q ? Contract.toSI(v.v, f.unit) : null,
                qa ? JSON.stringify(Contract.toSI(v.v, f.unit)) : null,
                cat && typeof v.v !== "boolean" ? v.v : null,
                cat && typeof v.v === "boolean" ? flag(v.v) : null,
                v.tol !== undefined ? Contract.toSI(v.tol, f.unit) : null,
                extraKey ? v[extraKey] : null, v.src, v.conf, n0(v.note),
                q ? v.v : null, qa ? JSON.stringify(v.v) : null, n0(v.tol));
        }
        for (const [kind, c] of Object.entries(b.curves || {})) {
            curve.run(id, kind, Contract.toSI(c.rpmStart, "rpm"), Contract.toSI(c.rpmStep, "rpm"), Contract.toSI(c.scale, c.u), Contract.siUnit(c.u),
                c.rpmStart, c.rpmStep, c.scale, c.u, JSON.stringify(c.data), c.method, c.src, c.conf, n0(c.note));
        }
        (b.notes || []).forEach((t, j) => note.run(id, j, t));
        const advisable = new Set((art_b.runtime.fuelAdvice && art_b.runtime.fuelAdvice.advisable) || []);
        ((b.fuel && b.fuel.compat) || []).forEach((c, j) => compat.run(id, c.fuel, j, c.status, c.src, c.conf, n0(c.note), flag(advisable.has(c.fuel))));
        if (isVariant) {
            const row = art.catalog.rows.find((r) => r.id === b.id);
            fts.run(id, ...Search.ftsColumns(row));
        }
    });
}

/**
 * Is bikes.sqlite up to date with this build? (Compares the input fingerprint,
 * not bytes, because a different SQLite version writes different bytes.)
 * @returns {string[]} differences
 */
export function diffSqlite(art, file, driver) {
    if (!fs.existsSync(file)) return [`${path.relative(ROOT, file)} is missing`];
    const db = driver.open(file, { readonly: true });
    try {
        const meta = Object.fromEntries(db.prepare("SELECT key, value FROM meta").all().map((r) => [r.key, r.value]));
        const diffs = [];
        if (meta.db_format !== String(DB_FORMAT)) diffs.push(`bikes.sqlite has db format ${meta.db_format}, expected ${DB_FORMAT}`);
        if (meta.input_hash !== art.inputHash) diffs.push("bikes.sqlite was built from different data");
        if (meta.catalog_version !== art.catalog.version) diffs.push("bikes.sqlite has a different catalog version");
        return diffs;
    } catch (e) {
        return [`bikes.sqlite can't be read: ${e.message}`];
    } finally { db.close(); }
}

// ----------------------------------------------------------------------------
// Convenience: the whole build
// ----------------------------------------------------------------------------
/**
 * @param {{ dataDir?: string, publicDir?: string, dbFile?: string, skipSqlite?: boolean, prune?: boolean, driver?: string }} [opts]
 */
export async function build(opts = {}) {
    const input = loadCatalog(opts.dataDir || DATA);
    const art = buildArtifacts(input);
    // Load the SQLite driver before writing anything, so a missing driver fails cleanly.
    let driver = null;
    if (!opts.skipSqlite) driver = (await import("./sqlite-driver.mjs")).loadDriver({ driver: opts.driver });
    const pub = writePublic(art, opts.publicDir || DEFAULT_PUBLIC_DIR, { prune: opts.prune !== false });
    const db = driver ? writeSqlite(art, input.ref, opts.dbFile || DEFAULT_DB_FILE, driver) : null;
    return { art, pub, db };
}

/** catalog.json + bundles only (no SQLite) — used by scripts/build-native.mjs. */
export function buildPublicOnly(opts = {}) {
    const art = buildArtifacts(loadCatalog(opts.dataDir || DATA));
    return { art, pub: writePublic(art, opts.publicDir || DEFAULT_PUBLIC_DIR, { prune: opts.prune !== false }) };
}
